### ISSUE TITLE
ことはじめ

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/SuspensionModel#1]
以下、2020/05/27に正田さんから送信されたメールの内容を、リンク先を追加する等して、載せる。

 ## 現状の詳細

剛体モデル（SUMCON）のモデルはあります。ヒートリンクや諸々入ったやつです。データはSVNに上げました。SUMCON以下の`./save/TypeA/ETMX_wHL200212.m`がそれに相当します[1]。

#### SUMCONモデルからSimulink modelへのコンバージョン
三代君は知っていると思いますが、Simulinkの中ではsys1というstate-spaceのパラメータで剛体モデルを読み込んでいます。`TypeAETMX_wHL2020012.m (SUMCON)`= `sys1 (MATLAB)`です。sys1はDropbox上にあって、ワークステーションでは`/kagra/Dropbox/Subsystems/VIS/Scripts/SuspensionControlModel/script/TypeA_wHL/ETMXmdl_realparams.mat`の中に`sys1`という名前で保存されています[2]。

#### Control model
現在のfilter bankや指定した時間のgainの情報を直接読んでSimulink上のパラメータに割り振ってくれる
model+codeがすでにあります。
`/kagra/Dropbox/Subsystems/VIS/Scripts/SuspensionControlModel/script/SUS/TypeAsimctrl_MB.slx`
がSimulink modelです[3]。ただしアップデートの途中なのでまだ変更（確認）が必要です。あとBPcombは入ってないです。

現在のコントロール情報以外のパラメータ（gainとか）は`ETMXmdl_realparams.mat`に入っています。ただし、actuator efficiencyのパラメータはOplevで得られるものだけ測定からフィットした値が入っています。ほかの自由度はDCで1m/countになるような値が入ってるはずです。

今のコントロール情報を読みだしてこのモデル上のパラメータに割り振るコードは全くドキュメントになっていませんが
`/kagra/Dropbox/Subsystems/VIS/Scripts/SuspensionControlModel/script/LoadModel_dampedTM.m`
あたりがサンプルコードです[4]。全く説明がなくて申し訳ないですが…。

[1] https://granite.phys.s.u-tokyo.ac.jp/svn/LCGT/trunk/VIS/sumcon/save/TypeA/ETMX_wHL200212.m
[2] https://www.dropbox.com/home/Subsystems/VIS/Scripts/SuspensionControlModel/script/TypeA_wHL?preview=ETMXwoHLmdl_realparams.mat
[3] https://www.dropbox.com/home/Subsystems/VIS/Scripts/SuspensionControlModel/script/SUS?preview=typeAsimctrl_NB.slx
[4] https://www.dropbox.com/home/Subsystems/VIS/Scripts/SuspensionControlModel/script?preview=LoadModel_dampedTM.m

## TO DO
とりあえず剛体モデルまではあるので、
 - [ ] Simulink配線の確認 #2 
 - [ ] BPcomb pathも足す?? #3
 - [ ] Actuation efficiencyをアップデート #4
 - [ ] センサー・アクチュエータノイズ情報をまとめる #5
あたりでしょうか。

**Comment by MiyoKouseki** [comment]
とりあえず、TODOをIssueに追加したので、Closeする。

**Comment by MiyoKouseki** [comment]
`ETMXmdl_realparams.mat`を読み込むとエラーが出る。

```
>> main
Warning: Variable 'data' originally saved as a DttData cannot be instantiated as an
object and will be read in as a uint32. 
> In main (line 16) 
Error using dlinmod (line 198)
Error evaluating parameter 'sys' in
'controlmodel/TypeA/Controller/BFservo/Servo_LBF/BF_DAMP_L'

Error in linmod (line 59)
[varargout{1:max(1,nargout)}] = dlinmod(model, Ts, varargin{:}, Args);

Error in main (line 22)
linss = linmod(mdlfile);
Caused by:
    Error using dlinmod (line 198)
    Cannot find an exact (case-sensitive) match for 'Filt'

    The closest match is: filt in
    /Applications/MATLAB_R2018b.app/toolbox/control/ctrlmodels/filt.m
```

**Comment by AyakaAShoda** [comment]
あー、これバージョンエラーですね。
ごめんない。k1scriptでロードしようとするとそれ起こるの忘れてた。
とりあえずMATLAB 2020aなら読み込めるはず。

**Comment by AyakaAShoda** [comment]
すみませんバージョンエラーじゃないかも。（k1scriptで読み込めました。）
バージョンの違いのせいで読み込みがうまくいかないのはsysc0のなかのInput, Outputの文字列だけでした。
（これはsysc0=ss***の関数で復活します）
