### ISSUE TITLE
IP control upgrade (sensor correction, sensor blending)

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/SuspensionModel#18]
[from here](https://www.dropbox.com/s/hoadb73fdyah02c/Post-O3%20task.xlsx?dl=0)

**Comment by AyakaAShoda** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14803
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14802
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14801
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14800
