### ISSUE TITLE
Simulink配線の確認

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/SuspensionModel#2]
#1 からのIssue

**Comment by AyakaAShoda** [comment]
・BPcombは足した
あと足りないの：
・Oplev path to BF

**Comment by AyakaAShoda** [comment]
Oplev path to BFは使われてないっぽいので無視しました。

**Comment by AyakaAShoda** [comment]
I think it is done.

**Comment by MiyoKouseki** [comment]
I did not review it. but I think it is done.
