### ISSUE TITLE
Actuation efficiencyをアップデート

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/SuspensionModel#4]
#1 から

**Comment by MiyoKouseki** [comment]
Is it done by Ushiba-san? 
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14512

**Comment by AyakaAShoda** [comment]
It is inconsistent with the loop design, and largely different from Ushiba-kun's original slide.
[klog](http://klog.icrr.u-tokyo.ac.jp/osl/?r=14621)
It might be because it is measured with IX?

**Comment by AyakaAShoda** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=14864
